name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: cachix/cachix-action@v12
      with:
        name: tweag-webauthn
        authToken: '${{ secrets.CACHIX_TWEAG_WEBAUTHN_AUTH_TOKEN }}'

    - name: "Nix build"
      run: nix-build -A webauthn -A server

  dev:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: cachix/cachix-action@v12
      with:
        name: tweag-webauthn
        authToken: '${{ secrets.CACHIX_TWEAG_WEBAUTHN_AUTH_TOKEN }}'

    - name: "Install Nix bash"
      run: nix-env -f . -iA pkgs.bash

    - name: "Nix shell"
      run: nix-shell --run "echo Success"

    - name: "Cabal build and test"
      run: nix-shell --run "cabal run test:tests"

    - name: "Style check"
      run: nix-shell --run "bin/autoformat.sh"
